package com.pbph.pcc.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.pbph.pcc.db.User;
import com.pbph.pcc.db.ShoppingCarP;
import com.pbph.pcc.db.ShoppingCarC;
import com.pbph.pcc.db.ShopSearchRecord;

import com.pbph.pcc.db.UserDao;
import com.pbph.pcc.db.ShoppingCarPDao;
import com.pbph.pcc.db.ShoppingCarCDao;
import com.pbph.pcc.db.ShopSearchRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig shoppingCarPDaoConfig;
    private final DaoConfig shoppingCarCDaoConfig;
    private final DaoConfig shopSearchRecordDaoConfig;

    private final UserDao userDao;
    private final ShoppingCarPDao shoppingCarPDao;
    private final ShoppingCarCDao shoppingCarCDao;
    private final ShopSearchRecordDao shopSearchRecordDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        shoppingCarPDaoConfig = daoConfigMap.get(ShoppingCarPDao.class).clone();
        shoppingCarPDaoConfig.initIdentityScope(type);

        shoppingCarCDaoConfig = daoConfigMap.get(ShoppingCarCDao.class).clone();
        shoppingCarCDaoConfig.initIdentityScope(type);

        shopSearchRecordDaoConfig = daoConfigMap.get(ShopSearchRecordDao.class).clone();
        shopSearchRecordDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        shoppingCarPDao = new ShoppingCarPDao(shoppingCarPDaoConfig, this);
        shoppingCarCDao = new ShoppingCarCDao(shoppingCarCDaoConfig, this);
        shopSearchRecordDao = new ShopSearchRecordDao(shopSearchRecordDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(ShoppingCarP.class, shoppingCarPDao);
        registerDao(ShoppingCarC.class, shoppingCarCDao);
        registerDao(ShopSearchRecord.class, shopSearchRecordDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        shoppingCarPDaoConfig.getIdentityScope().clear();
        shoppingCarCDaoConfig.getIdentityScope().clear();
        shopSearchRecordDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ShoppingCarPDao getShoppingCarPDao() {
        return shoppingCarPDao;
    }

    public ShoppingCarCDao getShoppingCarCDao() {
        return shoppingCarCDao;
    }

    public ShopSearchRecordDao getShopSearchRecordDao() {
        return shopSearchRecordDao;
    }

}
