package com.pbph.pcc.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SHOPPING_CAR_P.
 */
public class ShoppingCarP {

    private Long id;
    private String shopName;
    private String shopId;
    private String schoolId;
    private String userId;
    private String shopImgUrl;
    private Boolean shopIsChecked;
    private Double totlePrice;
    private Double shippingAmount;
    private Integer takeStoreNum;
    private Double takeSoodsPrice;
    private Double takeSoodsPrices;

    public ShoppingCarP() {
    }

    public ShoppingCarP(Long id) {
        this.id = id;
    }

    public ShoppingCarP(Long id, String shopName, String shopId, String schoolId, String userId, String shopImgUrl, Boolean shopIsChecked, Double totlePrice, Double shippingAmount, Integer takeStoreNum, Double takeSoodsPrice, Double takeSoodsPrices) {
        this.id = id;
        this.shopName = shopName;
        this.shopId = shopId;
        this.schoolId = schoolId;
        this.userId = userId;
        this.shopImgUrl = shopImgUrl;
        this.shopIsChecked = shopIsChecked;
        this.totlePrice = totlePrice;
        this.shippingAmount = shippingAmount;
        this.takeStoreNum = takeStoreNum;
        this.takeSoodsPrice = takeSoodsPrice;
        this.takeSoodsPrices = takeSoodsPrices;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getShopName() {
        return shopName;
    }

    public void setShopName(String shopName) {
        this.shopName = shopName;
    }

    public String getShopId() {
        return shopId;
    }

    public void setShopId(String shopId) {
        this.shopId = shopId;
    }

    public String getSchoolId() {
        return schoolId;
    }

    public void setSchoolId(String schoolId) {
        this.schoolId = schoolId;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getShopImgUrl() {
        return shopImgUrl;
    }

    public void setShopImgUrl(String shopImgUrl) {
        this.shopImgUrl = shopImgUrl;
    }

    public Boolean getShopIsChecked() {
        return shopIsChecked;
    }

    public void setShopIsChecked(Boolean shopIsChecked) {
        this.shopIsChecked = shopIsChecked;
    }

    public Double getTotlePrice() {
        return totlePrice;
    }

    public void setTotlePrice(Double totlePrice) {
        this.totlePrice = totlePrice;
    }

    public Double getShippingAmount() {
        return shippingAmount;
    }

    public void setShippingAmount(Double shippingAmount) {
        this.shippingAmount = shippingAmount;
    }

    public Integer getTakeStoreNum() {
        return takeStoreNum;
    }

    public void setTakeStoreNum(Integer takeStoreNum) {
        this.takeStoreNum = takeStoreNum;
    }

    public Double getTakeSoodsPrice() {
        return takeSoodsPrice;
    }

    public void setTakeSoodsPrice(Double takeSoodsPrice) {
        this.takeSoodsPrice = takeSoodsPrice;
    }

    public Double getTakeSoodsPrices() {
        return takeSoodsPrices;
    }

    public void setTakeSoodsPrices(Double takeSoodsPrices) {
        this.takeSoodsPrices = takeSoodsPrices;
    }

}
