package com.pbph.pcc.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SHOP_SEARCH_RECORD.
 */
public class ShopSearchRecord {

    private Long id;
    private String searchName;
    private java.util.Date createTime;
    private Integer searchType;

    public ShopSearchRecord() {
    }

    public ShopSearchRecord(Long id) {
        this.id = id;
    }

    public ShopSearchRecord(Long id, String searchName, java.util.Date createTime, Integer searchType) {
        this.id = id;
        this.searchName = searchName;
        this.createTime = createTime;
        this.searchType = searchType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSearchName() {
        return searchName;
    }

    public void setSearchName(String searchName) {
        this.searchName = searchName;
    }

    public java.util.Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(java.util.Date createTime) {
        this.createTime = createTime;
    }

    public Integer getSearchType() {
        return searchType;
    }

    public void setSearchType(Integer searchType) {
        this.searchType = searchType;
    }

}
